services:
  bot:
    depends_on:
      - mysql
    restart: always
    build:
      dockerfile: build/Dockerfile
      context: .
      target: prod
    env_file:
      - .env.prod

  mysql:
    image: percona:8.0
    platform: linux/x86_64
    restart: always
    volumes:
      - planing-poker-db:/var/lib/mysql
    env_file:
      - .env.prod

volumes:
  planing-poker-db: ~
