services:
  bot:
    image: texnicii/planning-poker-bot:latest
    platform: linux/amd64
    depends_on:
      - mysql
    restart: always
    env_file:
      - .env.prod

  mysql:
    image: percona:8.0
    platform: linux/x86_64
    restart: always
    volumes:
      - planning-poker-db:/var/lib/mysql
    env_file:
      - .env.prod

volumes:
  planning-poker-db: ~
