services:
  mysql:
    image: percona:8.0
    platform: linux/x86_64
    restart: always
    volumes:
      - planning-poker-db:/var/lib/mysql
    ports:
      - "63306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

volumes:
  planning-poker-db: ~
