// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package translations

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en_GB": &dictionary{index: en_GBIndex, data: en_GBData},
		"ru_RU": &dictionary{index: ru_RUIndex, data: ru_RUData},
	}
	fallback := language.MustParse("en-GB")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"Menu":           3,
	"Next ":          2,
	"Planning Poker": 0,
	"Reveal":         1,
}

var en_GBIndex = []uint32{ // 5 elements
	0x00000000, 0x0000000f, 0x00000016, 0x00000020,
	0x00000025,
} // Size: 44 bytes

const en_GBData string = "\x02Planning Poker\x02Reveal\x04\x00\x01 \x05\x02Next\x02Menu"

var ru_RUIndex = []uint32{ // 5 elements
	0x00000000, 0x00000024, 0x00000033, 0x00000043,
	0x0000004c,
} // Size: 44 bytes

const ru_RUData string = "" + // Size: 76 bytes
	"\x02Покер планирование\x02Открыть\x04\x00\x01 \x0b\x02Далее\x02Меню"

	// Total table size 201 bytes (0KiB); checksum: C56C7EFD
